---
resources:
  - name: cf-redis-broker
    type: git
    source:
      uri: https://github.com/pivotal-cf/cf-redis-broker
      branch: master

jobs:
- name: tests
  plan:
  - get: cf-redis-broker
    trigger: true
  - task: test-redis-broker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cflondonservices/london-services-ci-redis
          tag: 2.1.0
      inputs:
        - name: cf-redis-broker
          path: src/github.com/pivotal-cf/cf-redis-broker
      params:
        AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
      run:
        path: src/github.com/pivotal-cf/cf-redis-broker/ci/test-redis-broker.sh
