language: go

go:
- 1.2
- 1.2.1
- tip

before_install:
- export PATH=$HOME/gopath/bin:$PWD/Godeps/_workspace/bin:$PATH
- export GOPATH=$PWD/Godeps/_workspace:$GOPATH

install:
- go install github.com/onsi/ginkgo/ginkgo

script:
- ginkgo -r
